FROM wordpress:latest

# Instala dependencias
RUN apt-get update && apt-get install -y \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Instala WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

# Set etorno de trabajo
WORKDIR /var/www/html

# Copia plugins
COPY backend/wp-content/plugins/pokemon-api /var/www/html/wp-content/plugins/pokemon-api/

# Habilita plugins cuando inicie WrodPress
# Esto se agrega al script de punto de entrada que se ejecuta en el inicio del contenedor
RUN echo "wp plugin activate pokemon-api --allow-root" >> /usr/local/bin/activate-plugins.sh \
    && chmod +x /usr/local/bin/activate-plugins.sh

# Configurar WordPress para el acceso a la API REST
# Configurar WordPress para el acceso a la API REST
COPY enable-cors.php /var/www/html/wp-content/mu-plugins/enable-cors.php

# Configurar el punto de entrada para activar el plugin
COPY docker-entrypoint-custom.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint-custom.sh

# Punto de entrada personalizada
ENTRYPOINT ["docker-entrypoint-custom.sh"]
CMD ["apache2-foreground"]
