# Construcción
FROM node:16 as build

WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto de la aplicación
COPY frontend/ ./

# Establecer variables de env
ARG REACT_APP_API_URL=http://backend:8000/wp-json/pokemon-api/v1
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

# Compila la aplicación
RUN npm run build

# Etapa de producción
FROM nginx:alpine

# Copia de recursos creados de la etapa de compilación
COPY --from=build /app/build /usr/share/nginx/html

# Copiar la configuración de nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exportar puerto
EXPOSE 80

# Inicia nginx
CMD ["nginx", "-g", "daemon off;"]
